from pyinfra.operations import apt

apt.packages(
    _sudo=True,
    name="Installing utilities",
    packages=[
        "7zip",
        "curl",
        "dnsutils",
        "fd-find",
        "git",
        "htop",
        "iptables",
        "jq",
        "lftp",
        "locate",
        "lsb-release",
        "lsof",
        "pigz",
        "pwgen",
        "rsync",
        "screen",
        "sudo",
        "telnet",
        "unzip",
        "wget",
        "whois",
        "zip",
        "zstd",
    ],
    latest=True,
    update=True,
)
